/* Disassembler for Intel 8080 machine code.
 * Written by Scott Andre for Emulator 101 tutorial
 * Created Nov 30 2016
 */

#include "disassembler8080.h"

#include <stdio.h>

/* I don't know the maximum size an instruction might be, but 16 characters should be enough. */
void disassemble(uint8_t *opcode, char *buffer) {
	switch(opcode[0]) {
		case 0x00: sprintf(buffer, "NOP"); break;
		case 0x01: sprintf(buffer, "LXI  B, #0x%.2x%.2x", opcode[2], opcode[1]); break;
		case 0x02: sprintf(buffer, "STAX B"); break;
		case 0x03: sprintf(buffer, "INX  B"); break;
		case 0x04: sprintf(buffer, "INR  B"); break;
		case 0x05: sprintf(buffer, "DCR  B"); break;
		case 0x06: sprintf(buffer, "MVI  B, #0x%.2x", opcode[1]); break;
		case 0x07: sprintf(buffer, "RLC"); break;
		case 0x09: sprintf(buffer, "DAD  B"); break;
		case 0x0a: sprintf(buffer, "LDAX B"); break;
		case 0x0b: sprintf(buffer, "DCX  B"); break;
		case 0x0c: sprintf(buffer, "INR  C"); break;
		case 0x0d: sprintf(buffer, "DCR  C"); break;
		case 0x0e: sprintf(buffer, "MVI  C, #0x%.2x", opcode[1]); break;
		case 0x0f: sprintf(buffer, "RRC"); break;
		case 0x11: sprintf(buffer, "LXI  D, #0x%.2x%.2x", opcode[2], opcode[1]); break;
		case 0x12: sprintf(buffer, "STAX D"); break;
		case 0x13: sprintf(buffer, "INX  D"); break;
		case 0x14: sprintf(buffer, "INR  D"); break;
		case 0x15: sprintf(buffer, "DCR  D"); break;
		case 0x16: sprintf(buffer, "MVI  D, #0x%.2x", opcode[1]); break;
		case 0x17: sprintf(buffer, "RAL"); break;
		case 0x19: sprintf(buffer, "DAD  D"); break;
		case 0x1a: sprintf(buffer, "LDAX D"); break;
		case 0x1b: sprintf(buffer, "DCX  D"); break;
		case 0x1c: sprintf(buffer, "INR  E"); break;
		case 0x1d: sprintf(buffer, "DCR  E"); break;
		case 0x1e: sprintf(buffer, "MVI  E, #0x%.2x", opcode[1]); break;
		case 0x1f: sprintf(buffer, "RAR"); break;
		case 0x20: sprintf(buffer, "RIM"); break;
		case 0x21: sprintf(buffer, "LXI  H, #0x%.2x%.2x", opcode[2], opcode[1]); break;
		case 0x22: sprintf(buffer, "SHLD $%.2x%.2x", opcode[2], opcode[1]); break;
		case 0x23: sprintf(buffer, "INX  H"); break;
		case 0x24: sprintf(buffer, "INR  H"); break;
		case 0x25: sprintf(buffer, "DCR  H"); break;
		case 0x26: sprintf(buffer, "MVI  H, #0x%.2x", opcode[1]); break;
		case 0x27: sprintf(buffer, "DAA"); break;
		case 0x29: sprintf(buffer, "DAD  H"); break;
		case 0x2a: sprintf(buffer, "LHLD $%.2x%.2x", opcode[2], opcode[1]); break;
		case 0x2b: sprintf(buffer, "DCX  H"); break;
		case 0x2c: sprintf(buffer, "INR  L"); break;
		case 0x2d: sprintf(buffer, "DCR  L"); break;
		case 0x2e: sprintf(buffer, "MVI  L, #0x%.2x", opcode[1]); break;
		case 0x2f: sprintf(buffer, "CMA"); break;
		case 0x30: sprintf(buffer, "SIM"); break;
		case 0x31: sprintf(buffer, "LXI  SP, #0x%.2x%.2x", opcode[2], opcode[1]); break;
		case 0x32: sprintf(buffer, "STA  $%.2x%.2x", opcode[2], opcode[1]); break;
		case 0x33: sprintf(buffer, "INX  SP"); break;
		case 0x34: sprintf(buffer, "INR  M"); break;
		case 0x35: sprintf(buffer, "DCR  M"); break;
		case 0x36: sprintf(buffer, "MVI  M, #0x%.2x", opcode[1]); break;
		case 0x37: sprintf(buffer, "STC"); break;
		case 0x39: sprintf(buffer, "DAD  SP"); break;
		case 0x3a: sprintf(buffer, "LDA  $%.2x%.2x", opcode[2], opcode[1]); break;
		case 0x3b: sprintf(buffer, "DCX  SP"); break;
		case 0x3c: sprintf(buffer, "INR  A"); break;
		case 0x3d: sprintf(buffer, "DCR  A"); break;
		case 0x3e: sprintf(buffer, "MVI  A, #0x%.2x", opcode[1]); break;
		case 0x3f: sprintf(buffer, "CMC"); break;
		case 0x40: sprintf(buffer, "MOV  B, B"); break;
		case 0x41: sprintf(buffer, "MOV  B, C"); break;
		case 0x42: sprintf(buffer, "MOV  B, D"); break;
		case 0x43: sprintf(buffer, "MOV  B, E"); break;
		case 0x44: sprintf(buffer, "MOV  B, H"); break;
		case 0x45: sprintf(buffer, "MOV  B, L"); break;
		case 0x46: sprintf(buffer, "MOV  B, M"); break;
		case 0x47: sprintf(buffer, "MOV  B, A"); break;
		case 0x48: sprintf(buffer, "MOV  C, B"); break;
		case 0x49: sprintf(buffer, "MOV  C, C"); break;
		case 0x4a: sprintf(buffer, "MOV  C, D"); break;
		case 0x4b: sprintf(buffer, "MOV  C, E"); break;
		case 0x4c: sprintf(buffer, "MOV  C, H"); break;
		case 0x4d: sprintf(buffer, "MOV  C, L"); break;
		case 0x4e: sprintf(buffer, "MOV  C, M"); break;
		case 0x4f: sprintf(buffer, "MOV  C, A"); break;
		case 0x50: sprintf(buffer, "MOV  D, B"); break;
		case 0x51: sprintf(buffer, "MOV  D, C"); break;
		case 0x52: sprintf(buffer, "MOV  D, D"); break;
		case 0x53: sprintf(buffer, "MOV  D, E"); break;
		case 0x54: sprintf(buffer, "MOV  D, H"); break;
		case 0x55: sprintf(buffer, "MOV  D, L"); break;
		case 0x56: sprintf(buffer, "MOV  D, M"); break;
		case 0x57: sprintf(buffer, "MOV  D, A"); break;
		case 0x58: sprintf(buffer, "MOV  E, B"); break;
		case 0x59: sprintf(buffer, "MOV  E, C"); break;
		case 0x5a: sprintf(buffer, "MOV  E, D"); break;
		case 0x5b: sprintf(buffer, "MOV  E, E"); break;
		case 0x5c: sprintf(buffer, "MOV  E, H"); break;
		case 0x5d: sprintf(buffer, "MOV  E, L"); break;
		case 0x5e: sprintf(buffer, "MOV  E, M"); break;
		case 0x5f: sprintf(buffer, "MOV  E, A"); break;
		case 0x60: sprintf(buffer, "MOV  H, B"); break;
		case 0x61: sprintf(buffer, "MOV  H, C"); break;
		case 0x62: sprintf(buffer, "MOV  H, D"); break;
		case 0x63: sprintf(buffer, "MOV  H, E"); break;
		case 0x64: sprintf(buffer, "MOV  H, H"); break;
		case 0x65: sprintf(buffer, "MOV  H, L"); break;
		case 0x66: sprintf(buffer, "MOV  H, M"); break;
		case 0x67: sprintf(buffer, "MOV  H, A"); break;
		case 0x68: sprintf(buffer, "MOV  L, B"); break;
		case 0x69: sprintf(buffer, "MOV  L, C"); break;
		case 0x6a: sprintf(buffer, "MOV  L, D"); break;
		case 0x6b: sprintf(buffer, "MOV  L, E"); break;
		case 0x6c: sprintf(buffer, "MOV  L, H"); break;
		case 0x6d: sprintf(buffer, "MOV  L, L"); break;
		case 0x6e: sprintf(buffer, "MOV  L, M"); break;
		case 0x6f: sprintf(buffer, "MOV  L, A"); break;
		case 0x70: sprintf(buffer, "MOV  M, B"); break;
		case 0x71: sprintf(buffer, "MOV  M, C"); break;
		case 0x72: sprintf(buffer, "MOV  M, D"); break;
		case 0x73: sprintf(buffer, "MOV  M, E"); break;
		case 0x74: sprintf(buffer, "MOV  M, H"); break;
		case 0x75: sprintf(buffer, "MOV  M, L"); break;
		case 0x76: sprintf(buffer, "HLT"); break;
		case 0x77: sprintf(buffer, "MOV  M, A"); break;
		case 0x78: sprintf(buffer, "MOV  A, B"); break;
		case 0x79: sprintf(buffer, "MOV  A, C"); break;
		case 0x7a: sprintf(buffer, "MOV  A, D"); break;
		case 0x7b: sprintf(buffer, "MOV  A, E"); break;
		case 0x7c: sprintf(buffer, "MOV  A, H"); break;
		case 0x7d: sprintf(buffer, "MOV  A, L"); break;
		case 0x7e: sprintf(buffer, "MOV  A, M"); break;
		case 0x7f: sprintf(buffer, "MOV  A, A"); break;
		case 0x80: sprintf(buffer, "ADD  B"); break;
		case 0x81: sprintf(buffer, "ADD  C"); break;
		case 0x82: sprintf(buffer, "ADD  D"); break;
		case 0x83: sprintf(buffer, "ADD  E"); break;
		case 0x84: sprintf(buffer, "ADD  H"); break;
		case 0x85: sprintf(buffer, "ADD  L"); break;
		case 0x86: sprintf(buffer, "ADD  M"); break;
		case 0x87: sprintf(buffer, "ADD  A"); break;
		case 0x88: sprintf(buffer, "ADC  B"); break;
		case 0x89: sprintf(buffer, "ADC  C"); break;
		case 0x8a: sprintf(buffer, "ADC  D"); break;
		case 0x8b: sprintf(buffer, "ADC  E"); break;
		case 0x8c: sprintf(buffer, "ADC  H"); break;
		case 0x8d: sprintf(buffer, "ADC  L"); break;
		case 0x8e: sprintf(buffer, "ADC  M"); break;
		case 0x8f: sprintf(buffer, "ADC  A"); break;
		case 0x90: sprintf(buffer, "SUB  B"); break;
		case 0x91: sprintf(buffer, "SUB  C"); break;
		case 0x92: sprintf(buffer, "SUB  D"); break;
		case 0x93: sprintf(buffer, "SUB  E"); break;
		case 0x94: sprintf(buffer, "SUB  H"); break;
		case 0x95: sprintf(buffer, "SUB  L"); break;
		case 0x96: sprintf(buffer, "SUB  M"); break;
		case 0x97: sprintf(buffer, "SUB  A"); break;
		case 0x98: sprintf(buffer, "SBB  B"); break;
		case 0x99: sprintf(buffer, "SBB  C"); break;
		case 0x9a: sprintf(buffer, "SBB  D"); break;
		case 0x9b: sprintf(buffer, "SBB  E"); break;
		case 0x9c: sprintf(buffer, "SBB  H"); break;
		case 0x9d: sprintf(buffer, "SBB  L"); break;
		case 0x9e: sprintf(buffer, "SBB  M"); break;
		case 0x9f: sprintf(buffer, "SBB  A"); break;
		case 0xa0: sprintf(buffer, "ANA  B"); break;
		case 0xa1: sprintf(buffer, "ANA  C"); break;
		case 0xa2: sprintf(buffer, "ANA  D"); break;
		case 0xa3: sprintf(buffer, "ANA  E"); break;
		case 0xa4: sprintf(buffer, "ANA  H"); break;
		case 0xa5: sprintf(buffer, "ANA  L"); break;
		case 0xa6: sprintf(buffer, "ANA  M"); break;
		case 0xa7: sprintf(buffer, "ANA  A"); break;
		case 0xa8: sprintf(buffer, "XRA  B"); break;
		case 0xa9: sprintf(buffer, "XRA  C"); break;
		case 0xaa: sprintf(buffer, "XRA  D"); break;
		case 0xab: sprintf(buffer, "XRA  E"); break;
		case 0xac: sprintf(buffer, "XRA  H"); break;
		case 0xad: sprintf(buffer, "XRA  L"); break;
		case 0xae: sprintf(buffer, "XRA  M"); break;
		case 0xaf: sprintf(buffer, "XRA  A"); break;
		case 0xb0: sprintf(buffer, "ORA  B"); break;
		case 0xb1: sprintf(buffer, "ORA  C"); break;
		case 0xb2: sprintf(buffer, "ORA  D"); break;
		case 0xb3: sprintf(buffer, "ORA  E"); break;
		case 0xb4: sprintf(buffer, "ORA  H"); break;
		case 0xb5: sprintf(buffer, "ORA  L"); break;
		case 0xb6: sprintf(buffer, "ORA  M"); break;
		case 0xb7: sprintf(buffer, "ORA  A"); break;
		case 0xb8: sprintf(buffer, "CMP  B"); break;
		case 0xb9: sprintf(buffer, "CMP  C"); break;
		case 0xba: sprintf(buffer, "CMP  D"); break;
		case 0xbb: sprintf(buffer, "CMP  E"); break;
		case 0xbc: sprintf(buffer, "CMP  H"); break;
		case 0xbd: sprintf(buffer, "CMP  L"); break;
		case 0xbe: sprintf(buffer, "CMP  M"); break;
		case 0xbf: sprintf(buffer, "CMP  A"); break;
		case 0xc0: sprintf(buffer, "RNZ"); break;
		case 0xc1: sprintf(buffer, "POP  B"); break;
		case 0xc2: sprintf(buffer, "JNZ  $%.2x%.2x", opcode[2], opcode[1]); break;
		case 0xc3: sprintf(buffer, "JMP  $%.2x%.2x", opcode[2], opcode[1]); break;
		case 0xc4: sprintf(buffer, "CNZ  $%.2x%.2x", opcode[2], opcode[1]); break;
		case 0xc5: sprintf(buffer, "PUSH B"); break;
		case 0xc6: sprintf(buffer, "ADI  #0x%.2x", opcode[1]); break;
		case 0xc7: sprintf(buffer, "RST  0"); break;
		case 0xc8: sprintf(buffer, "RZ"); break;
		case 0xc9: sprintf(buffer, "RET"); break;
		case 0xca: sprintf(buffer, "JZ   $%.2x%.2x", opcode[2], opcode[1]); break;
		case 0xcc: sprintf(buffer, "CZ   $%.2x%.2x", opcode[2], opcode[1]); break;
		case 0xcd: sprintf(buffer, "CALL $%.2x%.2x", opcode[2], opcode[1]); break;
		case 0xce: sprintf(buffer, "ACI  #0x%.2x", opcode[1]); break;
		case 0xcf: sprintf(buffer, "RST  1"); break;
		case 0xd0: sprintf(buffer, "RNC"); break;
		case 0xd1: sprintf(buffer, "POP  D"); break;
		case 0xd2: sprintf(buffer, "JNC  $%.2x%.2x", opcode[2], opcode[1]); break;
		case 0xd3: sprintf(buffer, "OUT  #0x%.2x", opcode[1]); break;
		case 0xd4: sprintf(buffer, "CNC  $%.2x%.2x", opcode[2], opcode[1]); break;
		case 0xd5: sprintf(buffer, "PUSH D"); break;
		case 0xd6: sprintf(buffer, "SUI  #0x%.2x", opcode[1]); break;
		case 0xd7: sprintf(buffer, "RST  2"); break;
		case 0xd8: sprintf(buffer, "RC"); break;
		case 0xda: sprintf(buffer, "JC   $%.2x%.2x", opcode[2], opcode[1]); break;
		case 0xdb: sprintf(buffer, "IN   #0x%.2x", opcode[1]); break;
		case 0xdc: sprintf(buffer, "CC   $%.2x%.2x", opcode[2], opcode[1]); break;
		case 0xde: sprintf(buffer, "SBI  #0x%.2x", opcode[1]); break;
		case 0xdf: sprintf(buffer, "RST  3"); break;
		case 0xe0: sprintf(buffer, "RPO"); break;
		case 0xe1: sprintf(buffer, "POP  H"); break;
		case 0xe2: sprintf(buffer, "JPO  $%.2x%.2x", opcode[2], opcode[1]); break;
		case 0xe3: sprintf(buffer, "XTHL"); break;
		case 0xe4: sprintf(buffer, "CPO  $%.2x%.2x", opcode[2], opcode[1]); break;
		case 0xe5: sprintf(buffer, "PUSH H"); break;
		case 0xe6: sprintf(buffer, "ANI  #0x%.2x", opcode[1]); break;
		case 0xe7: sprintf(buffer, "RST  4"); break;
		case 0xe8: sprintf(buffer, "RPE"); break;
		case 0xe9: sprintf(buffer, "PCHL"); break;
		case 0xea: sprintf(buffer, "JPE  $%.2x%.2x", opcode[2], opcode[1]); break;
		case 0xeb: sprintf(buffer, "XCHG"); break;
		case 0xec: sprintf(buffer, "CPE  $%.2x%.2x", opcode[2], opcode[1]); break;
		case 0xee: sprintf(buffer, "XRI  #0x%.2x", opcode[1]); break;
		case 0xef: sprintf(buffer, "RST  5"); break;
		case 0xf0: sprintf(buffer, "RP"); break;
		case 0xf1: sprintf(buffer, "POP  PSW"); break;
		case 0xf2: sprintf(buffer, "JP   $%.2x%.2x", opcode[2], opcode[1]); break;
		case 0xf3: sprintf(buffer, "DI"); break;
		case 0xf4: sprintf(buffer, "CP   $%.2x%.2x", opcode[2], opcode[1]); break;
		case 0xf5: sprintf(buffer, "PUSH PSW"); break;
		case 0xf6: sprintf(buffer, "ORI  #0x%.2x", opcode[1]); break;
		case 0xf7: sprintf(buffer, "RST  6"); break;
		case 0xf8: sprintf(buffer, "RM"); break;
		case 0xf9: sprintf(buffer, "SPHL"); break;
		case 0xfa: sprintf(buffer, "JM   $%.2x%.2x", opcode[2], opcode[1]); break;
		case 0xfb: sprintf(buffer, "EI"); break;
		case 0xfc: sprintf(buffer, "CM   $%.2x%.2x", opcode[2], opcode[1]); break;
		case 0xfe: sprintf(buffer, "CPI  #0x%.2x", opcode[1]); break;
		case 0xff: sprintf(buffer, "RST  7"); break;
		default:   sprintf(buffer, "invalid opcode %.2x", opcode[0]); break;
	}
}
